### ISSUE TITLE
Prevent exposing of db functions for global use

### ISSUE THREAD

**Issue by webcoderspeed** [webcoderspeed/speed-cache#5]
Explanation - If we don't prevent then inner functions for db interaction directly which is not good

### Stop exposing following function
- getKeys

**Comment by webcoderspeed** [comment]
@hugekontrast you wanna try it

**Comment by hugekontrast** [comment]
I would love to give it a shot! However, I don't have any experience with typescript. I've been doing all things in pure javascript up till now.

**Comment by webcoderspeed** [comment]
@hugekontrast https://github.com/webcoderspeed/speed-cache/issues/3 you can this one. just do the documentation 
like this https://www.npmjs.com/package/redis
