### ISSUE TITLE
Save the cache file any time new cache comes 

### ISSUE THREAD

**Issue by webcoderspeed** [webcoderspeed/speed-cache#6]
Explanation - If we don't save the cache in file and let it store in memory, it will later cause server loads because as currently we are storing the cache in in memory which will flushed every time we restart our server. 

### Things need to be done 
- Create a file and save the data in JSON format
- Create a function which on server restart automatically read the file and seed the data in cache again to prevent from server db load  
- Also make scheduler which will update the file data on cache expiry and be in sync with cache

**Comment by prasoonmhwr** [comment]
May I work on this

**Comment by kareemmahlees** [comment]
@webcoderspeed 
Hello, does this issue still exist?
If yes I am happy to help, just assign it to me 🙂

**Comment by webcoderspeed** [comment]
@kareemmahlees go ahead

**Comment by kareemmahlees** [comment]
@webcoderspeed if you could add the labels for hacktoberfest also that would be awesome 🙂
